const CONFIG = {
    introTitle: 'Người yêu ơi!',
    introDesc: ` You're an apple of my eyes `,
    btnIntro: 'không hiểu =)))',
    title: ' Cho thơm má ',
    desc: ' Khong thi minh hon moi =))) ',
    btnYes: ' Vângggg =)))) ',
    btnNo: 'Không, không có dễ dãi',
    question:' Và em vẫn luôn gọi anh là em bé ',
    btnReply: ' không thích thì vẫn phải nghe  ',
    reply: ' Cho em hon ma them 1 cai hon moi ',
    mess: ' Yêu anh 😀  ',
    messDesc: ' Đỗ ĐH nha! ',
    btnAccept: ' =))) ',
    messLink: 'https://www.facebook.com/manmailinhhh'
